In [3]:
#Load and First Look at the Data

import pandas as pd 
import numpy as np

df=pd.read_csv('../DATA/Raw/ai4i2020.csv')
print("Shape", df.shape)
display(df.head(5))

Shape (10000, 14)

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [4]:

print("--- Data Info ---")
df.info()

print("\n--- Missing Values ---")
print(df.isnull().sum())

print("\n--- Duplicate Rows ---")
print(df.duplicated().sum())

--- Data Info ---
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  str
 2   Type                     10000 non-null  str
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), str(2)
memory usage: 1.1 MB

--- Missing Values ---
UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

--- Duplicate Rows ---
0

In [5]:
# Overall failure indicator
print("--- Machine Failure (Overall) ---")
print(df['Machine failure'].value_counts())
print(f"Failure rate: "
      f"{df['Machine failure'].mean()*100:.2f}%")

# 5 specific failure types
failure_types = ['TWF', 'HDF', 'PWF', 'OSF', 'RNF']

print("\n--- Individual Failure Type Counts ---")
for col in failure_types:
    count = df[col].sum()
    pct = df[col].mean() * 100
    print(f"{col}: {count} occurrences ({pct:.2f}%)")

# Check overlap — can multiple failures happen at once?
print("\n--- Failure Overlap Check ---")
df['failure_count'] = df[failure_types].sum(axis=1)
print(df['failure_count'].value_counts().sort_index())

--- Machine Failure (Overall) ---
Machine failure
0    9661
1     339
Name: count, dtype: int64
Failure rate: 3.39%

--- Individual Failure Type Counts ---
TWF: 46 occurrences (0.46%)
HDF: 115 occurrences (1.15%)
PWF: 95 occurrences (0.95%)
OSF: 98 occurrences (0.98%)
RNF: 19 occurrences (0.19%)

--- Failure Overlap Check ---
failure_count
0    9652
1     324
2      23
3       1
Name: count, dtype: int64

In [6]:
sensor_cols = ['Air temperature [K]',
               'Process temperature [K]',
               'Rotational speed [rpm]',
               'Torque [Nm]',
               'Tool wear [min]']

print("--- Sensor Reading Summary ---")
display(df[sensor_cols].describe().round(2))

print("\n--- Product Type Distribution ---")
print(df['Type'].value_counts())

--- Sensor Reading Summary ---

,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min]
count,10000.0,10000.00,10000.00,10000.00,10000.00
mean,300.0,310.01,1538.78,39.99,107.95
std,2.0,1.48,179.28,9.97,63.65
min,295.3,305.70,1168.00,3.80,0.00
25%,298.3,308.80,1423.00,33.20,53.00
50%,300.1,310.10,1503.00,40.10,108.00
75%,301.5,311.10,1612.00,46.80,162.00
max,304.5,313.80,2886.00,76.60,253.00

--- Product Type Distribution ---
Type
L    6000
M    2997
H    1003
Name: count, dtype: int64